export const CollegeOfTheCanyons = [
  {
    personalPic: "./Seniors/Me.jpg",
    name: "Jeremy",
    major: "Computer Science",
    currentSchool: "UCSD",
    link: "https://www.linkedin.com/in/jeremy-s-750718287/",
    email: "Jeremy02012005@gmail.com",
    linkText: "Linkedin",
    infos:
      "20屆國際班畢業生，架構這個網站的人，假如有資訊工程、美國生活相關的問題都可以問我喔",
  },
  {
    personalPic: "./Seniors/defaultimg.jpg",
    name: "Alice",
    major: "Business Administration",
    currentSchool: "UCR",
    infos: "2021開始上線上課2023前往COC...",
  },
  {
    personalPic: "./Seniors/Linus.jpg",
    name: "吳申罡/ Linus",
    major: "Eletronic Engineering/電機系",
    currentSchool: "UCLA",
    link: "https://www.instagram.com/3.7.92.16_/",
    email: "linus.oxo.tt@gmail.com",
    linkText: "Instagram",
    infos: "",
  },
];

export const UMC = [
  {
    personalPic: "",
    name: "Samantha",
    major: "Business Administration",
    currentSchool: "UMC -> UofT",
    infos: "學姊",
    link: "",
    linkText: "Linkedin",
  },
  {
    personalPic: "",
    name: "Iris",
    major: "Business Management",
    currentSchool: "UMC -> UofT",
    infos: "Uoft...",
    link: "",
    linkText: "Linkedin",
  },
  {
    personalPic: "",
    name: "Esther",
    major: "Business Management",
    currentSchool: "UMC -> UofT",
    infos: "Uoft...",
    link: "",
    linkText: "Linkedin",
  },
];

export const RedDeer = [
  {
    personalPic: "",
    name: "Ray",
    major: "IDK",
    currentSchool: "RedDeer ->",
    infos: "20屆...",
    link: "",
    linkText: "Linkedin",
  },
  {
    personalPic: "./Seniors/RaphaelChenho.jpg",
    name: "Raphael Chenho",
    major: "物理化學系",
    currentSchool: "McMaster University",
    link: "https://www.instagram.com/raph._.shu?utm_source=ig_web_button_share_sheet&igsh=dnJkNm42MDk2Z2Y2",
    email: "chenhosu@gmail.com",
    linkText: "Instagram",
    infos: "紅鹿的第一個聯繫人脈，22屆國際班...",
  },
  {
    personalPic: "./Seniors/Minerva.jpg",
    name: "Minerva",
    major: "Digital Media/ Film/ Television Studies",
    currentSchool: "The University of Queensland",
    link: "https://www.instagram.com/gyu8922_/",
    email: "minervalin0418@gmail.com",
    linkText: "Instagram",
    infos: "",
  },
  {
    personalPic: "",
    name: "劉恩瑜/ Annie",
    major: "Commerce",
    currentSchool: "University of Melbourne",
    link: "",
    email: "ajsister06@gmail.com",
    linkText: "",
    infos: "我是24年從惠文和St.Joseph 畢業，目前人在墨爾本大學商科就讀",
  },
  {
    personalPic: "./Seniors/Jenny.jpg",
    name: "Jenny",
    major: "Accounting/ minor Finance",
    currentSchool: "University of Alberta",
    link: "https://www.instagram.com/jenny_sun0923/?hl=en",
    email: "",
    linkText: "Instagram",
    infos: "",
  },
  {
    personalPic: "./Seniors/Ivanka.jpg",
    name: "Ivanka",
    major: "Life science",
    currentSchool: "McMaster university",
    link: "https://www.instagram.com/_ivanka.c/",
    email: "ivanka20031224@gmail.com",
    linkText: "Instagram",
    infos: "",
  },
  {
    personalPic: "",
    name: "Vincent",
    major: "Computer Science",
    currentSchool: "RedDeer -> UofT",
    infos: "23屆國際班...",
    link: "",
    linkText: "Linkedin",
  },
];
