export const CollegeOfTheCanyons = [
  {
    personalPic: "",
    name: "Jeremy",
    major: "Computer Science",
    currentSchool: "UCSD",
    link: "https://www.linkedin.com/in/jeremy-s-750718287/",
    email: "Jeremy02012005@gmail.com",
    linkText: "Linkedin",
    infos: "The One who built this website",
  },
  {
    personalPic: "",
    name: "Alice",
    major: "Business Administration",
    currentSchool: "UCR",
    infos: "2021開始上線上課2023前往COC...",
  },
  {
    personalPic: "./Seniors/Linus.jpg",
    name: "吳申罡/ Linus",
    major: "Eletronic Engineering/電機系",
    currentSchool: "UCLA",
    link: "https://www.instagram.com/3.7.92.16_/",
    email: "linus.oxo.tt@gmail.com",
    linkText: "Instagram",
    infos: "",
  },
];

export const UMC = [
  {
    personalPic: "",
    name: "Samantha",
    major: "Business Administration",
    currentSchool: "UMC -> UofT",
    infos: "學姊",
    link: "",
    linkText: "Linkedin",
  },
  {
    personalPic: "",
    name: "Iris",
    major: "Business Management",
    currentSchool: "UMC -> UofT",
    infos: "Uoft...",
    link: "",
    linkText: "Linkedin",
  },
  {
    personalPic: "",
    name: "Esther",
    major: "Business Management",
    currentSchool: "UMC -> UofT",
    infos: "Uoft...",
    link: "",
    linkText: "Linkedin",
  },
];

export const RedDeer = [
  {
    personalPic: "",
    name: "Ray",
    major: "IDK",
    currentSchool: "RedDeer ->",
    infos: "20屆...",
    link: "",
    linkText: "Linkedin",
  },
  {
    personalPic: "./Seniors/RaphaelChenho.jpg",
    name: "Raphael Chenho",
    major: "物理化學系",
    currentSchool: "McMaster University",
    link: "https://www.instagram.com/raph._.shu?utm_source=ig_web_button_share_sheet&igsh=dnJkNm42MDk2Z2Y2",
    email: "chenhosu@gmail.com",
    linkText: "Instagram",
    infos: "紅鹿的第一個聯繫人脈，22屆國際班...",
  },
  {
    personalPic: "./Seniors/Minerva.jpg",
    name: "Minerva",
    major: "Digital Media/ Film/ Television Studies",
    currentSchool: "The University of Queensland",
    link: "https://www.instagram.com/gyu8922_/",
    email: "minervalin0418@gmail.com",
    linkText: "Instagram",
    infos: "",
  },
  {
    personalPic: "",
    name: "Annie",
    major: "Data Science",
    currentSchool: "RedDeer ->",
    infos: "21屆國際班...",
    link: "",
    linkText: "Linkedin",
  },
  {
    personalPic: "",
    name: "Vincent",
    major: "Computer Science",
    currentSchool: "RedDeer -> UofT",
    infos: "23屆國際班...",
    link: "",
    linkText: "Linkedin",
  },
];
