export const CollegeOfTheCanyons = [
    {
        personalPic: "",
        name: "Jeremy",
        major: "Computer Science",
        currentSchool:"COC -> UCSD",
        infos:"The One who built this website",
        link:"https://www.linkedin.com/in/jeremy-s-750718287/",
        email:"Jeremy02012005@gmail.com",
        linkText: "Linkedin",
    },
    {
        personalPic: "",
        name: "Alice",
        major: "Business Administration",
        currentSchool:"COC -> UCR",
        infos:"2021開始上線上課2023前往COC...",
    },
];

export const UMC = [
    {
      personalPic: "",
      name: "Samantha",
      major: "Business Administration",
      currentSchool:"UMC -> UofT",
      infos:"學姊",
      link:"",
      linkText: "Linkedin",
    },
    {
      personalPic: "",
      name: "Iris",
      major: "Business Management",
      currentSchool:"UMC -> UofT",
      infos:"Uoft...",
      link:"",
      linkText: "Linkedin",
    },
    {
      personalPic: "",
      name: "Esther",
      major: "Business Management",
      currentSchool:"UMC -> UofT",
      infos:"Uoft...",
      link:"",
      linkText: "Linkedin",
    },
];

export const RedDeer = [
    {
      personalPic: "",
      name: "Ray",
      major: "IDK",
      currentSchool:"RedDeer ->",
      infos:"20屆...",
      link:"",
      linkText: "Linkedin",
    },
    {
      personalPic: "./Seniors/RaphaelChenho.jpg",
      name: "Raphael Chenho",
      major: "物理化學系",
      currentSchool:"RedDeer -> 麥克馬斯特大學",
      link:"https://www.instagram.com/raph._.shu?utm_source=ig_web_button_share_sheet&igsh=dnJkNm42MDk2Z2Y2",
      email:"chenhosu@gmail.com",
      linkText: "Instagram",
      infos:"紅鹿的第一個聯繫人脈，22屆國際班",
    },
    {
      personalPic: "",
      name: "Minerva",
      major: "Film//",
      currentSchool:"RedDeer ->",
      infos:"21屆國際班...",
      link:"",
      linkText: "Linkedin",
    },
    {
      personalPic: "",
      name: "Annie",
      major: "Data Science",
      currentSchool:"RedDeer ->",
      infos:"21屆國際班...",
      link:"",
      linkText: "Linkedin",
    },
    {
      personalPic: "",
      name: "Vincent",
      major: "Computer Science",
      currentSchool:"RedDeer -> UofT",
      infos:"23屆國際班...",
      link:"",
      linkText: "Linkedin",
    },
];